- name: Install nginx repository
  copy:
    src: nginx.repo
    dest: /etc/yum.repos.d/nginx.repo
    mode: 0644

- name: Install nginx
  yum:
    name: nginx
    state: installed

- name: Remove default nginx vhost
  file:
    path: /etc/nginx/conf.d/default.conf
    state: absent
  notify: Reload nginx

- name: Install nginx confg
  template:
    src: nginx.conf
    dest: /etc/nginx/nginx.conf
  notify: Reload nginx

- name: Install certs
  copy:
    mode: 0640
    src: "{{ item.ssl_cert }}"
    dest: "{{ nginx_cert_directory }}/{{ item.ssl_cert | basename }}"
  when: item.ssl_cert|default(False)
  with_items: "{{ nginx_vhosts }}"
  notify: Restart nginx

- name: Install private keys
  copy:
    mode: 0640
    src: "{{ item.ssl_key }}"
    dest: "{{ nginx_cert_directory }}/{{ item.ssl_key | basename }}"
  when: item.ssl_key|default(False)
  with_items: "{{ nginx_vhosts }}"
  notify: Restart nginx

- name: Install vhost configs
  template:
    src: "{{ item.config_template }}"
    dest: "/etc/nginx/conf.d/{{ item.name }}.conf"
    mode: 0644
  with_items: "{{ nginx_vhosts }}"
  notify: Reload nginx

- name: Ensure that nginx is started & enabled
  service:
    name: nginx
    state: started
    enabled: yes